version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: valleydao-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: phlo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d phlo -U admin']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: valleydao-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
